# Generated by Django 3.2.13 on 2022-06-15 22:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Event',
        ),
    ]
